// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgyjqolliqmlsmvckiiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJneWpxb2xsaXFtbHNtdmNraWl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0ODE3NzQsImV4cCI6MjA1NjA1Nzc3NH0.94xD96KMQRSmMxLmnC2nEpM_F5v9pXTcrMQEn7DurYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);